function get_topics(){
let res=[];
res.push([]);
res[0].push('content');
res.push([]);
res[1].push('Your crush is picking his/her nose');
res[1].push('Your crush is peeing his/her pants');
res[1].push('Your crush is throwing up');
res[1].push('Your crush is being bullied');
res[1].push('Your crush is being rude to the shop employee');
res[1].push("Your crush's fart stinks");
res[1].push('Your crush has terrible grammar skills');
res[1].push('Your crush cannot speak politely to people');
res[1].push('Your crush is asking you out');
res[1].push("Your crush takes you out to a romantic dinner, but you end up at Macdonald's");
res[1].push('Bumping into your crush in front of the toilets');
res.push([]);
res[2].push('Accidentally burping in front of your crush');
res[2].push('Accidentally throwing up in front of your crush');
res[2].push('Accidentally farting in front of your crush');
res[2].push('Bumping into your crush in front of the toilets');
res.push([]);
res[3].push("Your crush takes you out to a romantic dinner, but you end up at Macdonald's");
res.push([]);
res[4].push('Avoiding to look your crush in the eyes');
res[4].push('Becoming cold when your crush starts talking to you');
res[4].push('Denying having a crush for someone it in front of other people');
res[4].push('Speaking ill of your crush in front of other people');
res[4].push('Recommending to your crush going out with someone else than you.');
res.push([]);
res[5].push('First love');
res[5].push('First relationship');
res[5].push('First date');
res[5].push('First kiss');
res[5].push('Holding hands');
res[5].push('First confession');
res.push([]);
res[6].push('Putting a box of tissue next to your bed "just in case"');
res[6].push('Putting a condom in your wallet, "just in case"');
res[6].push('Wearing your lucky underwear for the occasion');
res[6].push('Cutting your nail, "just in case"');
res[6].push('Masturbating before, "juste in case"');
res[6].push('Brushing your teeth again, "just in case"');
res.push([]);
res[7].push('At the hotel');
res[7].push('At the park');
res[7].push('At his house');
res[7].push('At her house');
res[7].push('Inside the car');
res[7].push('At school');
res[7].push('At work');
res.push([]);
res[8].push('Face to face');
res[8].push('From behind');
res[8].push('On his/her side');
res[8].push('From below');
res[8].push('From above');
res.push([]);
res[9].push('Masturbate in the toilet');
res[9].push('Masturbate at school');
res[9].push('Masturbate at work');
res[9].push('Masturbate with climbing poles');
res[9].push("Masturbate with a table's corner");
res[9].push("Masturbate on one's bed");
res.push([]);
res[10].push('Date');
res[10].push('Hug');
res[10].push('Kiss');
res[10].push('Holding hands');
res[10].push('Confession');
res.push([]);
res[11].push('A date suddenly canceled on D-day');
res[11].push('Becoming moody when rain starts to fall during a date');
res[11].push('Having other boyfriends/girlfriends at the same time');
res[11].push('Refusing to change your social network status from "single" to "taken"');
res[11].push('Lying to someone you met online about having a boyfriend/girlfriend');
res[11].push("Showing your partner's most embarrassing picture to your friends");
res[11].push("Discretely taking one bill or two from your partner's wallet");
res[11].push('Lying about pregnancy to your partner');
res[11].push("Purposely changing your hobbies to please your partner's");
res[11].push('Subsidizing your moneyless boyfriend/girlfriend by paying for everything');
res[11].push('Believing everything your partner says after being told sweet words');
res[11].push('Listening to every whim he/she says');
res[11].push('Believing that you owe something to your partner');
res[11].push('Always being the first to apologize to avoid another fight');
res.push([]);
res[12].push('A partner who gives you a nice massage');
res[12].push('A partner who comes to pick you up anywhere');
res[12].push('A partner who gives straightforward but useful advices');
res[12].push('A partner who cooks for you');
res[12].push('A partner who hugs you when you come back home from a very tough day');
res[12].push('A partner who always compliments your efforts');
res[12].push('A partner who cleans for you so that you can relax');
res[12].push('A partner who kindly lays an attentive ear to your complaints');
res[12].push('A partner who says "come here for a hug"');
res[12].push('A partner who can sleep anywhere, anytime');
res[12].push('A partner who enjoys food very much');
res[12].push('A partner sensitive to your perfume');
res[12].push('A partner who enjoys imitating different accents for fun');
res[12].push('A positive-minded partner');
res[12].push('A partner who says hilarious things in his/her sleep');
res[12].push('A partner who is spying on your phone');
res.push([]);
res[13].push('A partner who is spying on your phone');
res[13].push('A partner who is trying to get in touch with your friends/family/boss');
res[13].push("A partner who trows away all your ex's pictures");
res[13].push('A partner who is spying on your garbage to find signs of cheating');
res[13].push('Trying to figure out where your partner was doing yesterday');
res[13].push("Watching what's inside your partner's wallet/purse");
res[13].push("Snooping through your partner's browsing history");
res.push([]);
res[14].push('Criticizing other people just in front of your partner');
res[14].push('Making him/her do everything you desire');
res[14].push('Suddenly being invited by him/her for lunch');
res[14].push('Getting texts and replies more often than before');
res[14].push('More frequent skin-on-skin contacts from/to your partner');
res[14].push('Long phone conversations lasting the whole night');
res[14].push('Being asked to give personal advices about family');
res[14].push('Using the same spoon or fork');
res[14].push('Being attributed or giving a nickname');
res[14].push('More frequent eye contact');
res[14].push('Being asked or asking about a potential boyfriend/girlfriend');
res.push([]);
res[15].push('One-way love');
res[15].push('Long-distance relationship');
res[15].push('Heart broken');
res[15].push('Love triangle relationship with his/her friends');
res[15].push('A conflicting triangle relationship you want to win');
res[15].push('Being engaged while having another boyfriend/girlfriend');
res[15].push('Having several boyfriends/girlfriends');
res[15].push('Not finding "the one"');
res.push([]);
res[16].push('Pretending to complain when the main purpose is to brag about yourself');
res[16].push('Changing your voice pitch and way of talking in front of the other sex');
res[16].push('Having a totally different personality after becoming an official couple');
res[16].push('Someone who really likes skinships');
res[16].push("Being interested only in your friend's boyfriend/girlfriend");
res[16].push("Bragging about one's natural beauty assets");
res[16].push('Someone who only talks about himeself/herself');
res.push([]);
res[17].push('Someone with good hygiene');
res[17].push('Someone with good fashion sense');
res[17].push('Someone serious');
res[17].push('Someone rich');
res[17].push('Someone smart');
res[17].push('Someone very thoughful');
res[17].push('Someone very supportive');
res[17].push('Someone who is good at anything');
res[17].push('Someone careless');
res[17].push('Someone arrogant');
res.push([]);
res[18].push('Mask');
res[18].push('Sunglasses');
res[18].push('Glasses');
res[18].push('Suit');
res[18].push('Hat');
res[18].push('Blue jeans');
res.push([]);
res[19].push('Coffee');
res[19].push('Lemon tea');
res[19].push('Milk tea');
res[19].push('Green tea');
res[19].push('Oolong tea');
res[19].push('Cocoa');
res.push([]);
res[20].push('Wine');
res[20].push('Beer');
res[20].push('Japanese sake');
res[20].push('Whisky');
res[20].push('Plum sake');
res[20].push('Coffee');
res.push([]);
res[21].push('Apple');
res[21].push('Orange');
res[21].push('Peach');
res[21].push('Pear');
res[21].push('Grape');
res[21].push('Watermelon');
res[21].push('Melon');
res[21].push('Tomato');
res[21].push('Plum');
res.push([]);
res[22].push('Chinese cabbage');
res[22].push('Cabbage');
res[22].push('Lettuce');
res[22].push('Spinach');
res[22].push('Onion');
res[22].push('Green pepper');
res.push([]);
res[23].push('Curry');
res[23].push('Beef stew');
res[23].push('Ramen');
res[23].push('Noodles');
res[23].push('Spaghetti');
res[23].push('Ravioli');
res.push([]);
res[24].push('high-speed train');
res[24].push('Local train');
res[24].push('Bus');
res[24].push('Taxi');
res[24].push('Car');
res[24].push('Bicycle');
res.push([]);
res[25].push('Ambulance');
res[25].push('Fire truck');
res[25].push('Police car');
res[25].push('Tow truck');
res[25].push('Hearse');
res.push([]);
res[26].push('Accidentally wearing the same clothes as a friend');
res[26].push('Farting in front of people');
res[26].push('Burping in front of people');
res[26].push('Being caught reading a porn magazine by your family');
res[26].push('Thinking that a person is talking to you but he/she was talking to someone else');
res[26].push('Getting caught making weird faces in front of the mirror');
res[26].push('Trying to handshake someone you thought was an acquaintance, but happens to be a stranger');
res[26].push('While doing shopping, getting inside a fitting room before realizing someone was inside');
res[26].push('Believing nobody is around and starting to sing alone, but when you look back someone was making fun of you');
res[26].push('Forgetting your change at the cash register and leaving the shop without your money');
res[26].push('Forgetting your purchase at the cash register and leaving the shop without your stuff');
res[26].push('Being confident in farting silently, but ending up in letting go a massive one');
res[26].push('Rushing to get on a train just as it is about to leave and falling down in front of everyone');
res[26].push('Talking to someone you though was the shop clerk, but it was a client');
res[26].push('Talking to someone you though was the shop clerk, but it was a manikin');
res[26].push('Accidentally having a slip of the tongue');
res.push([]);
res[27].push("Realizing on social medias about a friend's party you haven't been invited to");
res[27].push('Being the only one of a group to not receive a gift');
res[27].push('For some reasons, always having an empty seat next to yours in the train');
res[27].push("Your bicycle's basket is being used as a garbage can by strangers");
res[27].push("Wanting to say a last goodbye before realizing the person's already gone");
res[27].push('Having a chewing gum stuck in your shoe');
res[27].push("When everyone's already eating but your order hasn't been brought yet");
res[27].push('Having a new haircut but nobody notices');
res[27].push('When nobody remembers your birthday');
res.push([]);
res[28].push('Someone who takes hours to press the shutter-release camera button');
res[28].push('Watching a movie with your family when a sex scene suddenly starts');
res[28].push("Forgetting to lock your toilet's door and somebody tries to get in");
res[28].push("Getting inside a toilet but someone's already inside");
res[28].push('Saying bad things about someone inside the bathroom when the person concerned comes out from a compartment');
res[28].push('Believing nobody is around and starting to sing alone, but when you look back someone was making fun of you');
res[28].push('Upsetting somebody because you guessed his/her age wrong by adding 10 years');
res[28].push('You get bitten by your friend\'s supposedly "nice dog"');
res[28].push('Having the same clothes as a friend');
res[28].push('Realizing being cheated on by your partner');
res[28].push('Giving up your seat to an old lady but being refused');
res[28].push('When a couple you know starts an argument in front of you');
res[28].push('Being alone with a stranger inside an elevator');
res[28].push("Not knowing what to talk about to your friend's friend");
res[28].push('When someone you hate is on the other side of the pedestrian crossing');
res.push([]);
res[29].push('Realizing there is no toilet paper after finishing your business');
res[29].push('Talking bad about someone who was in fact just standing behind you');
res[29].push("Realizing you don't have enough cash at the register");
res[29].push('Not finding your wallet');
res[29].push('Not finding your phone');
res[29].push("Not finding your house's keys");
res[29].push("Feeling you're being stared at from behind");
res[29].push("Unknown number's call on your cellphone in the middle of the night");
res[29].push("The door bell is ringing and it's 2 am");
res.push([]);
res[30].push('"By the way… Did I return the DVD I borrowed that was due until today?"');
res[30].push('"By the way… Did I lock my house before leaving this morning?"');
res[30].push('"By the way… Did I turn off my stove before leaving the house?"');
res[30].push('"By the way… Did I take my load of laundry out of the washing machine?"');
res[30].push('"By the way… Did I turn my iron off after using it?"');
res[30].push("Feeling you're being stared at from behind");
res[30].push("Unknown number's call on your cellphone in the middle of the night");
res[30].push("The door bell is ringing and it's 2 am");
res.push([]);
res[31].push('Someone who often scratches his butt or belly');
res[31].push('Killing every single fly and mosquito without mercy');
res[31].push('Having more and more grey hair');
res[31].push('Being less energetic than a few years ago');
res.push([]);
res[32].push('Starting to think more about money and long-term investment');
res[32].push('Not having enough space to sit down on the train');
res[32].push('Someone whose voice is too loud');
res[32].push('Someone with restless legs syndrome');
res[32].push('Someone with a singular way of laughing');
res.push([]);
res[33].push("Someone who can't hold a knife properly when eating");
res[33].push('Someone who eats with the mouth wide open');
res[33].push('Having a hole in your socks');
res[33].push('Leaving your space and chair dirty after having finished eating in a restaurant');
res[33].push('Not closing doors');
res[33].push('Not using your hands to cover a sneeze or a cough');
res[33].push('Always leaving the toilet seat up');
res[33].push('Always leaving the lights on');
res[33].push('Always leaving your dirty clothes all around the floor');
res[33].push('Someone whose handwriting is terrible');
res[33].push('Headphones that leak all the sound');
res.push([]);
res[34].push('Manspreading');
res[34].push('Refusing to give up your seat to the elderly');
res[34].push("People who overuse their bicycle's bell to get pedestrians out of their way");
res[34].push('Angrily swearing at anybody from your car');
res[34].push("Having a small nap at a home furniture's store");
res[34].push('Littering the train');
res[34].push('Spitting on the floor');
res[34].push('Snubbing a shop clerk');
res.push([]);
res[35].push('Starting to despise your alarm clock sound');
res[35].push('Waking up at 6 am on a Sunday');
res[35].push('Chasing after cats');
res[35].push('Getting nervous when seeing a police car');
res[35].push('Writing sentences with ketchup');
res.push([]);
res[36].push('Pretending to be asleep');
res[36].push('Saying "this world is too small for me"');
res[36].push('Saying "rules are made to be broken"');
res[36].push('Shivering from cold and saying "there is a spirit passing by"');
res[36].push("Saying : you're too little to understand adults stuff");
res[36].push('Trying to show off your skills in a foreign language at any occasion');
res[36].push('Taking selfies 50 times a day');
res[36].push('Looking at yourself in the mirror 50 time a day');
res[36].push('Touching your hair 50 times a day');
res.push([]);
res[37].push('Farting in front of people');
res[37].push('Burping in front of people');
res[37].push('Picking your nose in front of people');
res[37].push('Biting your fingernails in front of people');
res[37].push('When he/she says "let me have a bite", but the bite becomes 10 bites');
res.push([]);
res[38].push('"Have you gained some weight?"');
res[38].push('"Are you on your periods??"');
res[38].push('"You stayed inside the bathroom for a while. Were you pooping?"');
res[38].push('"Why don\'t you have a boyfriend/girlfriend?"');
res[38].push('"Why aren\'t you married yet?"');
res[38].push('"When are you going to have children?"');
res[38].push('"How many money do you have in your account?"');
res[38].push('"How much do you earn?"');
res[38].push('"You have nose hair!"');
res[38].push('"There\'s a booger hanging out of your nose!"');
res[38].push('"Did you just fart"');
res[38].push('"You could at least have made me taste it"');
res.push([]);
res[39].push('"Easy to open"');
res[39].push('"For your protection, follow these safe handling instructions"');
res[39].push('"Percent daily values are based on a 2,000 calorie diet"');
res[39].push('"Stir well before drinking"');
res[39].push('"Once opened, consume within 2 days"');
res.push([]);
res[40].push('Tyrannosaurus');
res[40].push('Mammoth');
res[40].push('Triceratops');
res[40].push('Pteranodon');
res[40].push('Brachiosaurus');
res[40].push('Mosasaurus');
res[40].push('Spinosaurus');
res.push([]);
res[41].push('Mammoth');
res[41].push('Elephant');
res[41].push('Hippopotamus');
res[41].push('Rhinoceros');
res[41].push('Horse');
res.push([]);
res[42].push('Wolf');
res[42].push('Dog');
res[42].push('Fox');
res[42].push('Wild dog');
res[42].push('Mouse');
res[42].push('Rabbit');
res.push([]);
res[43].push('Pigeon');
res[43].push('Sparrow');
res[43].push('Crow');
res[43].push('Owl');
res[43].push('Swallow');
res[43].push('Falcon');
res.push([]);
res[44].push('Cat');
res[44].push('Wild cat');
res[44].push('Tiger');
res[44].push('Lion');
res[44].push('Jaguar');
res[44].push('Panther');
res[44].push('Cheetah');
res[44].push('Puma');
res.push([]);
res[45].push('Dolphin');
res[45].push('Whale');
res[45].push('Killer whale');
res[45].push('Manta ray');
res[45].push('Sunfish');
res.push([]);
res[46].push('Lizard');
res[46].push('Iguana');
res[46].push('Turtle');
res[46].push('Crocodile');
res[46].push('Frog');
res.push([]);
res[47].push('Rhinoceros beetle');
res[47].push('Stag beetle');
res[47].push('Longicorn beetle');
res[47].push('Longhorn beetle');
res[47].push('Ladybug');
res[47].push('Snail');
res.push([]);
res[48].push('Cicada');
res[48].push('Cricket');
res[48].push('Bell cricket');
res[48].push('Grasshopper');
res[48].push('Mantis');
res.push([]);
res[49].push('Bee');
res[49].push('Fly');
res[49].push('Mosquito');
res[49].push('Flying ant');
res[49].push('Dragonfly');
res.push([]);
res[50].push('Buffalo');
res[50].push('Cow');
res[50].push('Horse');
res[50].push('Deer');
res[50].push('Boar');
res[50].push('Pork');
res[50].push('Sheep');
res[50].push('Bear');
res[50].push('Rabbit');
res.push([]);
res[51].push('Rose');
res[51].push('Tulip');
res[51].push('Morning glory');
res[51].push('Sunflower');
res[51].push('Pansy');
res[51].push('Margaret');
res[51].push('Sweet pea');
res[51].push('Lily');
res[51].push('Hydrangea');
res[51].push('Cosmos');
res.push([]);
res[52].push('Typhoon');
res[52].push('Thunder');
res[52].push('Tornade');
res[52].push('Windstorm');
res[52].push('Rainbow');
res[52].push('Aurora');
res.push([]);
res[53].push('River');
res[53].push('Waterfall');
res[53].push('Sea');
res[53].push('Mountain');
res[53].push('Valley');
res[53].push('Hill');
res[53].push('Lake');
res.push([]);
res[54].push('Using your entire eraser');
res[54].push('Using your entire pencil');
res[54].push('Using your textbook without a single graffiti');
res[54].push('Wearing short pants and a T-shirt for a class presentation');
res[54].push('Pretending to sing during music class when the teacher is away');
res[54].push("Purposely change a few answers cheating on a test by peeking into a classmate's answer sheet");
res.push([]);
res[55].push('When you give the wrong answer during the very first day of school');
res[55].push('Tripping over a jumping rope while playing');
res[55].push('Calling your teacher "mom" by accident');
res[55].push('Calling your friend "mom" by accident');
res[55].push('Peeing your pants');
res[55].push('Being assigned mean nicknames');
res[55].push('Entering the wrong classroom by accident');
res.push([]);
res[56].push('A teacher who will not start the class until complete');
res[56].push('A teacher who says "I don\'t have to raise you. I\'m not your mom/dad"');
res[56].push('A teacher who says "I will not get angry if you tell me the truth"');
res[56].push("A teacher who won't let you go use the bathroom");
res[56].push('A teacher who gets an answer wrong but tries to justify him/herself by saying "it was on purpose"');
res.push([]);
res[57].push('Fighting with an umbrella');
res[57].push('Fighting with a broom');
res[57].push('Riding a broom and pretending to be an evil witch');
res[57].push('Make hair stand up with static electricity');
res[57].push("Making piles with an eraser's shavings");
res[57].push('Hugging a friend');
res[57].push("Touching a friend's hair");
res[57].push("Kissing a friend's cheek");
res[57].push("Touching a friend's boobs");
res.push([]);
res[58].push('Making fun of someone who drinks milk');
res[58].push('Saying "awesome!" about anything');
res[58].push('You ask your teacher if he/she has a girlfriend/boyfriend');
res[58].push('You say "I will never ask for anything else" when asking a favor');
res[58].push('You say "give me ten billion dollars."');
res[58].push('Someone who always says "can you bet your life on it?" to anyone about anything');
res[58].push("Someone who reveals other people's crush name even though he/she promised not to");
res[58].push('When you say "I haven\'t studied for the test" even though you spent the night on getting ready');
res[58].push('When you purposely say "I failed the test" even though you got the highest score of the class');
res.push([]);
res[59].push('Someone who is always mean to his/her crush');
res[59].push('Someone who always says he/she is sick');
res[59].push('Someone who never pronounce the Spanish "r" correctly');
res[59].push('Someone who exclusively wears joggers');
res[59].push('Someone who wears short pants all year');
res[59].push('Someone who always goes to school infirmary');
res.push([]);
res[60].push('Group leader');
res[60].push('School kitchen staff');
res[60].push('Student council');
res.push([]);
res[61].push('Hiking excursion');
res[61].push('Field trip');
res[61].push('Factory tour');
res[61].push('Sports day');
res[61].push('School festival');
res[61].push('School excursion');
res[61].push('Swimming class');
res[61].push('Ski class');
res.push([]);
res[62].push('Class observation by parents');
res[62].push('Parent and child meeting');
res[62].push('Academic counseling');
res[62].push('Mock exam');
res[62].push('Class meeting');
res.push([]);
res[63].push('Pencil');
res[63].push('Highlighter pen');
res[63].push('Multi color pen');
res[63].push('mechanical pencil');
res[63].push('Ballpoint pen');
res[63].push('Red pen');
res[63].push('Brush');
res.push([]);
res[64].push("You put your alarm and wake up but realize there's no school today");
res[64].push("Thanks to bad weather conditions, there's no school today");
res[64].push("Thanks to a flu epidemic so there's no school today");
res[64].push("You know there'll be a transfer student when you go back to school from vacation");
res[64].push('The school marathon is called off because of rain');
res[64].push('The clock shows exactly 11:11 when you checked');
res[64].push('When you have one last dollar in your pocket to buy a chocolate bar');
res[64].push('You had the correct answer at a question you were certain to have failed');
res[64].push('You won the last round of rock-paper-scissors');
res[64].push('You randomly open your textbook and accidentally reach the right page you needed');
res[64].push('You nail to throw a ball into the garbage bin from a long distance and everyone goes wild');
res[64].push('The pedestrian light goes green right when arriving at the crossing');
res.push([]);
res[65].push('The teacher gives back grades in the decreasing order');
res[65].push('You will probably not have time to finish your assignment tonight');
res[65].push('Your stomach suddenly hurts at school');
res[65].push('You realized that you accidentally jumped one column answer on your test and everyting got displaced');
res[65].push('You realize 5 min before the end of the test that your question sheet was two-sided');
res[65].push("You're the only one being called to the principal's office");
res[65].push("You forget it is gym day and you don't have your sporting equipment");
res[65].push('Your stomach starts to gurgle right when the classroom goes silent');
res.push([]);
res[66].push('Your pencil lead breaks right when you need to write');
res[66].push('When people keep talking about their brothers/sisters in class');
res[66].push('Because of the rain, your textbook gets all wet');
res[66].push('You get to use THE only shaky desk of the classroom');
res[66].push("When you're given the same seat after a new seating order");
res[66].push('When you play hide-and-seek but nobody finds you and they forget and leave');
res[66].push("When nobody wants you and you're the last to be chosen for a team");
res[66].push('When no one wants to be paired up with you and you end up with the teacher');
res[66].push('When you play a game but nobody is passing you the ball');
res[66].push('When you get the only kickboard that has a hole in it');
res[66].push("When you're the only one getting scolded by the teacher even if everyone is noisy");
res[66].push('Nobody remembers your birthday');
res.push([]);
res[67].push('"Santa will not come if you\'re being bad!"');
res[67].push('"Sorry honey, they do not sell replacement batteries for that toy."');
res[67].push('"You\'re not our child, we adopted you."');
res[67].push('"There is no carrot (your most hated food) in that soup so hurry up and drink it!"');
res[67].push('"If you eat enough vegetables, your body makes them taste like candy."');
res.push([]);
res[68].push("Someone at your table who is the only one to order a dessert, even though you're at the restaurant with a lot of people");
res[68].push("Someone at your table who is the only one to order an appetizer, even though you're at the restaurant with a lot of people");
res[68].push("Someone at your table who is the only one to order alcohol, even though you're at the restaurant with a lot of people");
res[68].push("Someone at your table who orders nothing but water, even though you're at the restaurant with a lot of people");
res[68].push("Someone at your table who keeps watching his/her phone, even though you're at the restaurant with a lot of people");
res[68].push("Someone who wastes everbody's time to split the bill down to the last penny at the restaurant");
res[68].push('Someone who tries to pay less than what he/she has ordered at the restaurant when splitting the bill');
res.push([]);
res[69].push('A partner who leaves you 30 min at the restaurant table to go to the bathroom during a date');
res[69].push('A partner who criticizes your food habits at the restaurant during a date');
res[69].push('A partner who takes from your plate without asking at the restaurant');
res[69].push('A partner who checks out the waitress/waiter during a date');
res[69].push('A partner who tells you how beautiful/handsome the waitress/waiter is during a date');
res[69].push('A partner who asks you to split the bill after a dinner at a fancy restaurant');
res[69].push('A partner who criticizes the dish you chose at the restaurant');
res.push([]);
res[70].push('Someone who burps at the restaurant');
res[70].push('Someone who farts at the restaurant');
res[70].push('Someone who picks his/her nose at the restaurant');
res[70].push('Someone who behaves badly towards the staff at the restaurant');
res[70].push('Someone who starts smoking inside a restaurant');
res[70].push('Someone who asks you "do you mind if I smoke?" after lighting up a cigarette');
res.push([]);
res[71].push("Someone at the school canteen who carefuly watches for people who don't finish their lunches");
res[71].push('Someone at the school canteen who eats all the leftovers');
res[71].push('Someone at the school canteen who always wastes food');
res[71].push('Someone at the school canteen who lies about alergies so he/she can get away with wasting food');
res[71].push('Someone at the school canteen who pressures other students into eating faster because he/she wants to go to play');
res[71].push('Someone at the school canteen who is a picky eater');
res.push([]);
res[72].push('A partner who keeps looking at his/her phone during a date');
res[72].push('A partner who hides his/her phone screen when receiving a message during a date');
res[72].push('A partner who only talks about himself/herself during a date');
res[72].push('A partner who checks out other girls/guys during a date');
res[72].push('A partner who talks about ex boyfriends/ex girlfriends during a date');
res[72].push("A partner who shows you ex boyfriends/ex girlfriends' pictures during a date");
res[72].push('A partner who suddenly answers the phone and leaves you during a date');
res[72].push('A partner who only talks about his/her favorite actors/actresses during a date');
res.push([]);
res[73].push('A lying client who pays with a 10$ bill at a restaurant but claims to have handled the staff 50$');
res[73].push('A client who lies about having a hair in his/her food to eat for free');
res[73].push('A client who lies about having a bug in his/her food to eat for free');
res[73].push("A client who lies about not receiving his/her money change at the restaurant's cash register");
res[73].push('A client who lies about getting food poisening at a restaurant to receive financial compensation');
res.push([]);
res[74].push('Getting in a very dirty and stinky public bathroom stall');
res[74].push("The restaurant table you arrived at hasn't been cleaned up");
res[74].push('The person before you forgot to flush the toilet');
res[74].push('The person before you clogged the toilet');
res[74].push('The person before you left pee stains on toilet seat');
res[74].push("A man/woman uses the other gender's public restroom");
res[74].push('Being stuck in a very long line at public restroom');
res.push([]);
res[75].push('The restaurant table you arrived at is squeeky clean');
res[75].push('The public toilet you went at HAS soap and it smells GOOD');
res[75].push('The public toilet you went at has high-technology sanitary seats');
res[75].push('The public toilet you went at is squeeky clean');
res[75].push('The public toilet you went at has high-technology hand dryers');
res[75].push('There is no waiting line to get in the public toilet');
res[75].push('The public toilet you went at has a separate powder room');
res.push([]);
res[76].push('Doing it at school');
res[76].push('Doing it at work');
res[76].push('Doing it in a public place');
res[76].push('Doing it at te gym');
res[76].push("Doing it at your parents' house");
res[76].push('Doing it in the shower');
res[76].push('Doing it in the car');
res[76].push('Doing it in a golf course');
res.push([]);
res[77].push('Sweating when doing it');
res[77].push('Moaning when doing it');
res[77].push('Screaming when doing it');
res[77].push('Crying when doing it');
res[77].push('Having deep facial expressions when doing it');
res[77].push('Being emotionless when doing it');
res.push([]);
res[78].push('Moving fast when doing it');
res[78].push('Moving slowly when doing it');
res[78].push('Moving harder when doing it');
res[78].push('Being immobile when doing it');
res[78].push('Being dedicated when doing it');
res[78].push('Being passive when doing it');
res.push([]);
res[79].push('Noticing you forgot to write your name on your copy AFTER the exam');
res[79].push('Noticing you forgot to write your student number on your copy AFTER the exam');
res[79].push("Noticing you mispelled your teacher's name on your copy AFTER the exam");
res[79].push('Noticing you mispelled your own name on your copy AFTER the exam');
res[79].push('Noticing you misunderstood a question AFTER handing your exam paper');
res[79].push('Noticing there were also questions on the back of the paper 5 min after the end of the exam');
res.push([]);
res[80].push('First coffee');
res[80].push('First soda');
res[80].push('First liquor');
res[80].push('First beer');
res[80].push('First French wine');
res[80].push('First breast milk');
res[80].push('First Japanese sake');
res.push([]);
res[81].push('First thunder');
res[81].push('First snow');
res[81].push('First typhoon');
res[81].push('First rain');
res[81].push('First earthquake');
res[81].push('First full moon');
res[81].push('First lunar eclipse');
res[81].push('First solar eclipse');
res[81].push('First hail storm');
res[81].push('First flowering cherry trees');
res[81].push('First heat wave');
res.push([]);
res[82].push('First spicy curry taste');
res[82].push('First mustard taste');
res[82].push('First wasabi taste');
res[82].push('First ginger taste');
res[82].push('First lemon taste');
res[82].push('First red cayenne pepper');
res.push([]);
res[83].push('Boobs');
res[83].push('Tits');
res[83].push('Hips');
res[83].push('Huge breasts');
res[83].push('Small breasts');
res.push([]);
res[84].push('Boobs');
res[84].push('Butt');
res[84].push('Hips');
res[84].push('Huge breasts');
res[84].push('Thighs');
res[84].push('Calf');
res[84].push('Arms');
res[84].push('Belly');
res[84].push('Lips');
res.push([]);
res[85].push('Muscle');
res[85].push('Nape of the neck');
res[85].push('Back of the neck');
res[85].push('Thigh');
res[85].push('Collarbone');
res[85].push('Back');
res[85].push('Fingertips');
res[85].push('Hair');
res.push([]);
res[86].push('I like doing it alone');
res[86].push('I like doing it with someone');
res[86].push('I like threeways');
res[86].push('I like being observed doing it');
res[86].push('I like observing people doing it');
res.push([]);
res[87].push('I like them big');
res[87].push('I like them soft');
res[87].push('I like them hard');
res[87].push('I like them shapely');
res[87].push('I like them skinny');
res.push([]);
res[88].push('Sexual appetite');
res[88].push('Appetite');
res[88].push('Wanting to sleep');
res[88].push('Wanting to pee');
res[88].push('Wanting to poo');
res[88].push('Thirst');
res.push([]);
res[89].push('School gym clothes');
res[89].push('School uniform');
res[89].push('Leotard');
res[89].push('Swim suit');
res[89].push('Lab coat');
res[89].push('Suit');
res.push([]);
res[90].push('Hiccup');
res[90].push('Cough');
res[90].push('Sneeze');
res[90].push('Runny nose');
res[90].push('Burp');
res[90].push('Yawn');
res[90].push('Tinnitus');
res.push([]);
res[91].push('Forgetting your homework and ending up doing it the last day before submission day');
res[91].push("Asking your teacher the day before the test about course concepts you didn't get");
res[91].push('Not doing anything for your class presentation and ending up preparing roughly something the night before');
res[91].push("Faking sickness to avoid a test you didn't study for");
res[91].push('Receving instructions to handle a school paper before 12 pm, and ending up submitting it at 11:59');
res.push([]);
res[92].push('Chocolate eclairs');
res[92].push('Cream puffs');
res[92].push('Cream-stuffed pastries');
res[92].push('Ice cream');
res.push([]);
res[93].push('Permanent makeup');
res[93].push('Permanent hair removal');
res[93].push('Curly hair permanent');
res[93].push('Diet');
res[93].push('Hair coloring');
res[93].push('Straight hair permanent');
res.push([]);
res[94].push('Confessing your love by e-mail');
res[94].push('Confessing your love on the phone');
res[94].push('Confessing your love through an instant messaging app');
res[94].push('Confessing your love at a cafe');
res[94].push('Confessing your love at the beach');
res[94].push('Confessing your love at the movie theater');
res[94].push('Confessing your love at the restaurant');
res.push([]);
res[95].push('Festival');
res[95].push('Barbecue');
res[95].push('Fireworks');
res.push([]);
res[96].push('Parent-teacher communication notebook');
res[96].push('Diary');
res[96].push('Letter');
res[96].push('Cheat sheet');
res[96].push('Class pet journal');
res.push([]);
res[97].push('Office romance');
res[97].push('teacher student romance');
res[97].push('Doctor patient romance');
res[97].push('Boss employee romance');
res[97].push('Brother sister romance');
res[97].push('Romance between cousins');
res[97].push('Romance between a prince/princess and a commoner');
res.push([]);
res[98].push('Body soap');
res[98].push('Soap bar');
res[98].push('Dish detergent');
res[98].push('Laundry detergent');
res[98].push('Shampoo');
res[98].push('Rinse');
res[98].push('Conditioner');
res.push([]);
res[99].push('Grilled meat');
res[99].push('Slow cooked meat');
res[99].push('Kebab');
res[99].push('Hamburg');
res[99].push('Steak');
res.push([]);
res[100].push('Carrot');
res[100].push('Radish');
res[100].push('Lotus root');
res[100].push('Turnip');
res[100].push('Burdock root');
res.push([]);
res[101].push('Blood test');
res[101].push('Urine test');
res[101].push('Stool test');
res[101].push('Tuberculosis screening');
res[101].push('X-rays');
res.push([]);
res[102].push('Abandoned cat');
res[102].push('Abandoned dog');
res[102].push('Heartbroken best friend');
res[102].push('A best friend who failed an entrance exam');
res.push([]);
res[103].push('Aroma therapy oil');
res[103].push('Aromatic candle');
res[103].push('Air freshener');
res[103].push('Air fragrance');
res[103].push('Perfume');
res[103].push('Incense stick');
res[103].push('Mosquito repellent');
res[103].push('Bug spray');
res.push([]);
res[104].push('Sunscreen');
res[104].push('Toner');
res[104].push('Moisturizing cream');
res[104].push('Lip cream');
res[104].push('Face soap');
res[104].push('Foundation');
res.push([]);
res[105].push('Face powder');
res[105].push('Lipstick');
res[105].push('Eye shadow');
res[105].push('Powder blush');
res[105].push('Mascara');
res[105].push('Fake eyelashes');
res.push([]);
res[106].push('Someone careless');
res[106].push('Someone arrogant');
res[106].push('Someone with restless legs syndrome');
res[106].push('Someone unhygienic');
res[106].push('Someone insane');
res[106].push('Someone weird');
res[106].push('Someone stingy');
res[106].push('Someone short tempered');
res[106].push('An attention whore person');
res[106].push('Someone too naive');
res.push([]);
res[107].push('Demon');
res[107].push('Ghost');
res[107].push('Ogre');
res[107].push('Goblin');
res[107].push('God');
res.push([]);
res[108].push('Space');
res[108].push('Sky');
res[108].push('Heaven');
res[108].push('Roof');
res.push([]);
res[109].push('Love');
res[109].push('Friendship');
res[109].push('Trust');
res[109].push('Effort');
res[109].push('Jealousy');
res.push([]);
res[110].push('Light');
res[110].push('Sound');
res[110].push('Heat');
res[110].push('Ultraviolet rays');
res[110].push('Electromagnetic waves');
res[110].push('Air');
res.push([]);
res[111].push('Shooting star');
res[111].push('Sun');
res[111].push('Space');
res[111].push('Satellite');
res[111].push('Cloud');
res.push([]);
res[112].push('Hourglass');
res[112].push('Wristwatch');
res[112].push('Stopwatch');
res[112].push('Pendulum clock');
res[112].push('Wall clock');
res.push([]);
res[113].push('Angel');
res[113].push('Godness');
res[113].push('Elf');
res[113].push('Holy Mother');
res[113].push('Gremlin');
res.push([]);
res[114].push('Sky');
res[114].push('Heaven');
res[114].push('Reincarnation');
res[114].push('Post-mortem');
res[114].push('Previous life');
res[114].push('Hell');
res.push([]);
res[115].push('Hot (weather)');
res[115].push('Thickness');
res[115].push('Hot (thing, person)');
res[115].push('Weight');
res.push([]);
res[116].push('Curiosity');
res[116].push('Mischief');
res[116].push('Phobia');
res[116].push('Politeness');
res[116].push('Kindness');
res.push([]);
res[117].push('Battlefield');
res[117].push('Hell');
res[117].push('Prison');
res[117].push('Abandoned mine');
res.push([]);
res[118].push('Gold');
res[118].push('Silver');
res[118].push('Precious stone');
res[118].push('Money');
res[118].push('Ring (for fingers)');
res[118].push('Picture');
res.push([]);
res[119].push('Jealousy');
res[119].push('admiration (towards...)');
res[119].push('Crush');
res[119].push('Love at first sight');
res[119].push('Paternal/maternal love');
res.push([]);
res[120].push('Oil');
res[120].push('Water');
res[120].push('Soy sauce');
res[120].push('Vinegar');
res[120].push('Chicken stock');
res[120].push('Cooking alcohol');
res.push([]);
res[121].push('Dinosaur');
res[121].push('Beast');
res[121].push('Wolf');
res[121].push('Werewolf');
res.push([]);
res[122].push('Bully');
res[122].push('Quarrel');
res[122].push('Prank');
res[122].push('Dictatorship');
res.push([]);
res[123].push('Trap');
res[123].push('Grave');
res[123].push('Root cellar');
res[123].push('Cave');
res[123].push('Warehouse');
res.push([]);
res[124].push('Hotspring');
res[124].push('Fountain');
res[124].push('Geyser');
res[124].push('Waterfall');
res.push([]);
res[125].push('Fire');
res[125].push('Flame');
res[125].push('Magma');
res[125].push('Lava');
res[125].push('Volcanic ash');
res.push([]);
res[126].push('Cell (biology)');
res[126].push('Atom');
res[126].push('Molecule');
res[126].push('Microorganism');
res.push([]);
res[127].push('To read');
res[127].push('To study');
res[127].push('To learn by heart');
res[127].push('To listen carefully');
res[127].push('Classroom chatter');
res.push([]);
res[128].push('Mirror');
res[128].push('Glass');
res[128].push('Pocket mirror');
res[128].push('Floor mirror');
res[128].push('Mirror sticker');
res.push([]);
res[129].push('Basement');
res[129].push('Tunnel');
res[129].push('Catacombs');
res[129].push('Ditch (infrastructure)');
res.push([]);
res[130].push('Vampire');
res[130].push('Werewolf');
res[130].push('Undead');
res[130].push('Zombie');
res.push([]);
res[131].push('Gambling');
res[131].push('Stock price');
res[131].push('Casino');
res.push([]);
res[132].push('Medicine');
res[132].push('Aspirin');
res[132].push('Laxative');
res[132].push('Nasal spray');
res[132].push('Eye drops');
res[132].push('Alcohol');
res.push([]);
res[133].push('Footbridge');
res[133].push('Escalator');
res[133].push('Elevator');
res[133].push('Roller coaster');
res.push([]);
res[134].push('Anime cosplay');
res[134].push('Animal costume');
res[134].push('Costume');
res.push([]);
res[135].push('Soup');
res[135].push('Smoothie');
res[135].push('Pot-au-feu (French dish)');
res[135].push('Pho (Vietnamese dish)');
res.push([]);
res[136].push('Colored contact lenses');
res[136].push('Sunglasses');
res[136].push('Corrective contact lenses');
res[136].push('Glasses');
res.push([]);
res[137].push('Wheelbarrow');
res[137].push('Electric bicycle');
res[137].push('Mini truck');
res[137].push('Shopping cart/trolley');
res.push([]);
res[138].push('Coin flipping');
res[138].push('Rock-paper-scissors');
res[138].push('Dice');
res.push([]);
res[139].push('Hairpin');
res[139].push('Rubber band');
res[139].push('Hair band');
res[139].push('Scrunchie (for hair)');
res[139].push('Hair clip');
res.push([]);
res[140].push('Clown');
res[140].push('Magician');
res[140].push('Juggler');
res[140].push('Fire breathing');
res.push([]);
res[141].push('Present');
res[141].push('Bento (Japanese lunch box)');
res[141].push('Gift box');
res[141].push('Individually wrapped snacks');
res.push([]);
res[142].push('Helicopter');
res[142].push('Jet aircraft');
res[142].push('Airplane');
res[142].push('Hot air balloon');
res[142].push('UFO');
res[142].push('Drone');
res[142].push('Spaceship');
res[142].push('Orbiter');
res.push([]);
res[143].push('Cityhall');
res[143].push('Post office');
res[143].push('Convenience store');
res[143].push('Supermarket');
res[143].push('Drugstore');
res.push([]);
res[144].push('Yacht');
res[144].push('Sailing ship');
res[144].push('Kayak');
res[144].push('Cruise ship');
res.push([]);
res[145].push('Amateur');
res[145].push('Minor (under 18)');
res[145].push('Brat');
res[145].push('Immature girl');
res[145].push('Immature boy');
res.push([]);
res[146].push('"No drinking"');
res[146].push('"No smoking"');
res[146].push('"No swimming"');
res[146].push('"No fishing"');
res[146].push('"No shoes inside"');
res.push([]);
res[147].push('Bookmark');
res[147].push('Family photo album');
res[147].push('Book cover');
res[147].push('Bookbinding');
return res;
}
